spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/driver_booking_app
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.admin.email=admin@goride.com
app.admin.password=admin123
